[package]
name = "lehmer-rng"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mylib"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
rand_core = "0.6.4"
